package test.Unit;

import java.util.ArrayList;

import test.Heuristic;


import mage.Core.Oligo;
import test.Constants;
import mage.Tools.FASTA;

public class FreeEnergy {

	
	/**
	 * Creates a pool of oligos and prints out the DG values, and the corresponding oligos.
	 * The DG values for oligos that correspond to the oligos generated by Harris's optMAGE
	 * are checked for having the same DG values
	 * 
	 * @param args
	 * @throws Exception
	 */
	public static void main (String [] args) throws Exception {

		// Create a Genome that encapsulated the default genome that Harris has.
		String genome = FASTA.readFFN(Constants.blastdirectory,Oligo.Genome);
		Heuristic.verbose(false);
		mage.Switches.PrimaryScore.method =  2 ;
		Oligo.buffer_5prime= 35;
		Oligo.buffer_3prime= 15;
		mage.Switches.FreeEnergy.method = 2;
		mage.Switches.Blast.method = 2 ;
		System.out.println(genome.length());

		ArrayList <Oligo> pool =  new ArrayList<Oligo>();

		// Test pool of four oligos
		pool.add(Oligo.InsertionFactory(genome, "ATCG", 190, 2,true, "o3") );
		pool.add(Oligo.InsertionFactory(genome, "TTGG", 458, 2,true, "o2") );
		pool.add(Oligo.InsertionFactory(genome, "ATCGGCTCGAG", 1408, 2,true, "o1") );
		pool.add(Oligo.InsertionFactory(genome, "GGAATTAACCAA", 2349, 2,true, "o4") );
		
		
		// Calc DG and print, BG is calculated for verbose mode to print out stuff
		for (Oligo ol : pool) {
			ol.calc_bg();
			ol.calc_dg();
			System.out.println(ol.getBGasString());
			ol.calc_primaryScore();
			System.out.println(ol.getPrimaryScoreAsString());
			System.out.println(ol.getAsString());
		}
		
	}
}